### ISSUE TITLE
Need a functional video for this project

### ISSUE THREAD

**Issue by zhendi** [OpenCSGs/csghub#15]

**Comment by KinglyWayne** [comment]
https://github.com/OpenCSGs/csghub/assets/3232817/ad140679-5fa8-4012-9f86-baea64ab3d30

Here it is ：）

**Comment by KinglyWayne** [comment]
https://github.com/OpenCSGs/csghub/assets/3232817/205d07f2-de9d-4a7f-b3f5-83514a71453e

1080p version is here

**Comment by wanghh2000** [comment]
csghub有python的SDK开发包吗
