### ISSUE TITLE
git clone 下载模型时无法看到下载进度

### ISSUE THREAD

**Issue by Xiaolong-RRL** [OpenCSGs/CSGHub#176]
在opencsg.com上下载模型权重时，无法看到下载进度，是否可以考虑增加进度条显示？
```
git clone https://opencsg.com/models/AIWizards/Meta-Llama-3-8B-Instruct.git
```

![image](https://github.com/OpenCSGs/CSGHub/assets/74476562/65c5f898-8163-4057-9a43-e61e25ef5e60)

**Comment by hiveer** [comment]
@Xiaolong-RRL 是命令行，类似于 yarn add xxx 那种效果吗？

**Comment by KinglyWayne** [comment]
git协议默认不会显示，可以通过加入调试命令查看总体进度
`time GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git clone` 
如果需要更详细的进度，请等待后续我们的客户端sdk
