### ISSUE TITLE
使用过程中创建组织必须上传输logo，上传无效无法创建组织

### ISSUE THREAD

**Issue by yangjian615** [OpenCSGs/CSGHub#196]

**Comment by hiveer** [comment]
@yangjian615 感谢使用和贡献，我们会尽快跟进这个问题

**Comment by yangjian615** [comment]
如下图所示
![asd](https://github.com/OpenCSGs/CSGHub/assets/14069737/22f5a4ed-be18-4aa9-8729-20e4d21ca8f0)
