### ISSUE TITLE
离线无网络环境部署问题

### ISSUE THREAD

**Issue by yangjian615** [OpenCSGs/CSGHub#197]
离线无网络部署问题：
![image](https://github.com/OpenCSGs/CSGHub/assets/14069737/20a2c165-8331-4eb2-b617-95f84726e45a)
查看csghub_server服务日志error
![image](https://github.com/OpenCSGs/CSGHub/assets/14069737/cbf750df-d54a-43db-ba2c-eb4f9f63774a)
联网后正常使用请排查

**Comment by Rader** [comment]
@yangjian615 新版已经解决了离线部署的问题，如果仍然需要离线部署请升级到最新版。

这个 issue 先关掉了。
