### ISSUE TITLE
docker 无法查看opencsg-nginx-1组件的日志

### ISSUE THREAD

**Issue by wangkx0107** [OpenCSGs/CSGHub#21]
通过docker-cmpose一件部署csghub后，通过`docker logs -f opencsg-nginx-1 `查看组件的日志，一直hung住;但是进入到容器中的nginx的日志目录下是可以日志的；不过没有docker logs方便。

**Comment by Rader** [comment]
除了nginx，其它服务的日志能正常查看吗？

**Comment by pulltheflower** [comment]
@wangkx0107 您好，docker 的 `access.log` 和 `error.log` 被挂载到了当前目录的 `nginx/logs` 目录，您可以直接在宿主机当前目录的 `nginx/logs` 中查看到 `access.log` 和 `error.log`。
