### ISSUE TITLE
启动CSGHUB，页面提示加载模型数据报错

### ISSUE THREAD

**Issue by UberIzual** [OpenCSGs/CSGHub#247]
容器状态， git server为unhealth状态：
CONTAINER ID   IMAGE                                                                    COMMAND                  CREATED         STATUS                     PORTS                                                                                            NAMES
b0b74aa6738d   registry.cn-beijing.aliyuncs.com/opencsg_public/csghub_server:latest     "/starhub-bin/script…"   5 minutes ago   Up 5 minutes               0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                                        all_in_one-csghub_server-1
c749f8eedab2   registry.cn-beijing.aliyuncs.com/opencsg_public/csghub_portal:latest     "bash -c 'bundle exe…"   5 minutes ago   Up 5 minutes               0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                        all_in_one-csghub_portal-1
c3a9250fa4bd   registry.cn-beijing.aliyuncs.com/opencsg_public/csghub_git:latest        "/opt/bitnami/script…"   5 minutes ago   Up 5 minutes (unhealthy)   0.0.0.0:2222->2222/tcp, :::2222->2222/tcp, 0.0.0.0:3001->3001/tcp, :::3001->3001/tcp, 3000/tcp   all_in_one-gitea-1
9449fa12e891   registry.cn-beijing.aliyuncs.com/opencsg_public/csghub_postgres:latest   "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes (healthy)     0.0.0.0:5433->5432/tcp, :::5433->5432/tcp                                                        all_in_one-postgres-1
53b9c62d17a2   registry.cn-beijing.aliyuncs.com/opencsg_public/csghub_nginx:latest      "/docker-entrypoint.…"   5 minutes ago   Up 5 minutes               0.0.0.0:80->80/tcp, :::80->80/tcp                                                                all_in_one-nginx-1
3889ed82475b   registry.cn-beijing.aliyuncs.com/opencsg_public/csghub_minio:latest      "/opt/bitnami/script…"   5 minutes ago   Up 5 minutes               0.0.0.0:9000-9001->9000-9001/tcp, :::9000-9001->9000-9001/tcp                                    all_in_one-minio-1

csghub-git 日志：
gitea 08:59:21.13 INFO  ==> Gitea installation finished
gitea 08:59:21.13 DEBUG ==> Setting APP_NAME to 'git' in Gitea configuration
gitea 08:59:21.14 DEBUG ==> Setting RUN_USER to 'git' in Gitea configuration
gitea 08:59:21.15 DEBUG ==> Setting RUN_MODE to 'prod' in Gitea configuration
gitea 08:59:21.16 DEBUG ==> Setting database.DB_TYPE to 'postgres' in Gitea configuration
gitea 08:59:21.16 DEBUG ==> Setting database.HOST to 'postgres:5432' in Gitea configuration
gitea 08:59:21.17 DEBUG ==> Setting database.NAME to 'gitea' in Gitea configuration
gitea 08:59:21.18 DEBUG ==> Setting database.USER to 'postgres' in Gitea configuration
gitea 08:59:21.19 DEBUG ==> Setting database.PASSWD to 'sdfa23Sh!322' in Gitea configuration
gitea 08:59:21.19 DEBUG ==> Setting database.SSL_MODE to 'disable' in Gitea configuration
gitea 08:59:21.20 DEBUG ==> Setting server.DOMAIN to '192.168.0.41/gitserver' in Gitea configuration
gitea 08:59:21.21 DEBUG ==> Setting server.PROTOCOL to 'http' in Gitea configuration
gitea 08:59:21.21 DEBUG ==> Setting server.ROOT_URL to 'http://192.168.0.41/gitserver' in Gitea configuration
gitea 08:59:21.22 DEBUG ==> Setting server.SSH_DOMAIN to '192.168.0.41' in Gitea configuration
gitea 08:59:21.23 DEBUG ==> Setting server.SSH_PORT to '2222' in Gitea configuration
gitea 08:59:21.23 DEBUG ==> Setting server.SSH_LISTEN_PORT to '2222' in Gitea configuration
gitea 08:59:21.24 DEBUG ==> Setting server.HTTP_PORT to '3001' in Gitea configuration
gitea 08:59:21.25 DEBUG ==> Setting log.ROOT_PATH to '/opt/bitnami/gitea/tmp/log' in Gitea configuration
gitea 08:59:21.25 DEBUG ==> Setting repository.ROOT to '/opt/bitnami/gitea/data/git/repositories' in Gitea configuration
gitea 08:59:21.26 DEBUG ==> Setting security.PASSWORD_HASH_ALGO to 'pbkdf2' in Gitea configuration
gitea 08:59:21.27 DEBUG ==> Setting mailer.ENABLED to 'false' in Gitea configuration
gitea 08:59:21.28 DEBUG ==> Setting lfs.PATH to '/opt/bitnami/gitea/data/lfs' in Gitea configuration
gitea 08:59:21.28 DEBUG ==> Setting lfs.STORAGE_TYPE to 'minio' in Gitea configuration
gitea 08:59:21.29 DEBUG ==> Setting lfs.MINIO_ACCESS_KEY_ID to 'admin' in Gitea configuration
gitea 08:59:21.30 DEBUG ==> Setting lfs.MINIO_SECRET_ACCESS_KEY to 'Password_123' in Gitea configuration
gitea 08:59:21.30 DEBUG ==> Setting lfs.MINIO_ENDPOINT to 'minio:9000' in Gitea configuration
gitea 08:59:21.31 DEBUG ==> Setting lfs.MINIO_BUCKET to 'opencsg-server-lfs' in Gitea configuration
gitea 08:59:21.32 DEBUG ==> Setting lfs.MINIO_LOCATION to 'cn-beijing' in Gitea configuration
gitea 08:59:21.32 DEBUG ==> Setting lfs.MINIO_USE_SSL to 'false' in Gitea configuration
gitea 08:59:21.33 DEBUG ==> Setting service.DEFAULT_ALLOW_CREATE_ORGANIZATION to 'true' in Gitea configuration
gitea 08:59:21.34 DEBUG ==> Setting service.DISABLE_REGISTRATION to 'false' in Gitea configuration
gitea 08:59:21.34 DEBUG ==> Setting ssh.minimum_key_sizes.RSA to '1023' in Gitea configuration
gitea 08:59:21.35 INFO  ==> Persisting Gitea installation
gitea 08:59:21.38 INFO  ==> ** Gitea setup finished! **

gitea 08:59:21.38 INFO  ==> ** Starting Gitea **
2024/06/12 08:59:21 .../setting/security.go:166:loadSecurityFrom() [W] Enabling Query API Auth tokens is not recommended. DISABLE_QUERY_AUTH_TOKEN will default to true in gitea 1.23 and will be removed in gitea 1.24.
2024/06/12 08:59:21 cmd/web.go:242:runWeb() [I] Starting Gitea on PID: 1
2024/06/12 08:59:21 cmd/web.go:111:showWebStartupMessage() [I] Gitea version: 34105e75f built with GNU Make 4.3, go1.21.5 : bindata
2024/06/12 08:59:21 cmd/web.go:112:showWebStartupMessage() [I] * RunMode: prod
2024/06/12 08:59:21 cmd/web.go:113:showWebStartupMessage() [I] * AppPath: /opt/bitnami/gitea/bin/gitea
2024/06/12 08:59:21 cmd/web.go:114:showWebStartupMessage() [I] * WorkPath: /opt/bitnami/gitea
2024/06/12 08:59:21 cmd/web.go:115:showWebStartupMessage() [I] * CustomPath: /opt/bitnami/gitea/custom
2024/06/12 08:59:21 cmd/web.go:116:showWebStartupMessage() [I] * ConfigFile: /opt/bitnami/gitea/custom/conf/app.ini
2024/06/12 08:59:21 cmd/web.go:117:showWebStartupMessage() [I] Prepare to run install page
2024/06/12 08:59:21 cmd/web.go:304:listen() [I] Listen: http://0.0.0.0:3001/gitserver
2024/06/12 08:59:21 cmd/web.go:308:listen() [I] AppURL(ROOT_URL): http://192.168.0.41/gitserver/
2024/06/12 08:59:21 ...s/graceful/server.go:50:NewServer() [I] Starting new Web server: tcp:0.0.0.0:3001 on PID: 1

csghub-server 日志:
Waiting for Gitea service to be ready...

csghub-portal 日志报错：

Started GET "/internal_api/codes?page=1&per_page=16&search=&sort=trending&task_tag=&framework_tag=&language_tag=&license_tag=" for 192.168.112.18 at 2024-06-12 09:00:06 +0000
Cannot render console from 192.168.112.18! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by InternalApi::CodesController#index as */*
  Parameters: {"page"=>"1", "per_page"=>"16", "search"=>"", "sort"=>"trending", "task_tag"=>"", "framework_tag"=>"", "language_tag"=>"", "license_tag"=>""}
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."login_identity" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/helpers/sessions_helper.rb:11:in `current_user'
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."login_identity" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/helpers/sessions_helper.rb:11:in `current_user'
ETHON: performed EASY effective_url=http://csghub_server:8080/api/v1/codes?page=1&per=16&sort=trending response_code=502 return_code=ok total_time=0.337157
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."login_identity" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/helpers/sessions_helper.rb:11:in `current_user'
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."login_identity" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/helpers/sessions_helper.rb:11:in `current_user'
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."login_identity" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/helpers/sessions_helper.rb:11:in `current_user'
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."login_identity" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/helpers/sessions_helper.rb:11:in `current_user'
  TRANSACTION (0.1ms)  BEGIN
  ↳ app/controllers/application_controller.rb:54:in `log_error'
  ErrorLog Create (0.4ms)  INSERT INTO "error_logs" ("request", "payload", "user_info", "message", "created_at", "updated_at", "backtrace") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["request", "GET /internal_api/codes"], ["payload", "{\"page\"=>\"1\", \"per_page\"=>\"16\", \"search\"=>\"\", \"sort\"=>\"trending\", \"task_tag\"=>\"\", \"framework_tag\"=>\"\", \"language_tag\"=>\"\", \"license_tag\"=>\"\", \"controller\"=>\"internal_api/codes\", \"action\"=>\"index\"}"], ["user_info", " /  /  / "], ["message", ""], ["created_at", "2024-06-12 09:00:06.656285"], ["updated_at", "2024-06-12 09:00:06.656285"], ["backtrace", "[\"/myapp/app/services/starhub/shared_repo_apis.rb:52:in `get_repos'\", \"/myapp/app/services/starhub/code_apis.rb:16:in `get_codes'\", \"/myapp/app/controllers/internal_api/codes_controller.rb:10:in `index'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/abstract_controller/base.rb:215:in `process_action'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_controller/metal/rendering.rb:165:in `process_action'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/abstract_controller/callbacks.rb:234:in `block in process_action'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:118:in `block in run_callbacks'\", \"/usr/local/bundle/gems/actiontext-7.0.8/lib/action_text/rendering.rb:20:in `with_renderer'\", \"/usr/local/bundle/gems/actiontext-7.0.8/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:138:in `run_callbacks'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/abstract_controller/callbacks.rb:233:in `process_action'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_controller/metal/rescue.rb:23:in `process_action'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/notifications.rb:206:in `block in instrument'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/notifications.rb:206:in `instrument'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_controller/metal/instrumentation.rb:66:in `process_action'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'\", \"/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/railties/controller_runtime.rb:27:in `process_action'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/abstract_controller/base.rb:151:in `process'\", \"/usr/local/bundle/gems/actionview-7.0.8/lib/action_view/rendering.rb:39:in `process'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_controller/metal.rb:188:in `dispatch'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_controller/metal.rb:251:in `dispatch'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/routing/route_set.rb:32:in `serve'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/journey/router.rb:50:in `block in serve'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/journey/router.rb:32:in `each'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/journey/router.rb:32:in `serve'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/routing/route_set.rb:852:in `call'\", \"/usr/local/bundle/gems/rack-2.2.8/lib/rack/tempfile_reaper.rb:15:in `call'\", \"/usr/local/bundle/gems/rack-2.2.8/lib/rack/etag.rb:27:in `call'\", \"/usr/local/bundle/gems/rack-2.2.8/lib/rack/conditional_get.rb:27:in `call'\", \"/usr/local/bundle/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/http/permissions_policy.rb:38:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/http/content_security_policy.rb:36:in `call'\", \"/usr/local/bundle/gems/rack-2.2.8/lib/rack/session/abstract/id.rb:266:in `context'\", \"/usr/local/bundle/gems/rack-2.2.8/lib/rack/session/abstract/id.rb:260:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/cookies.rb:704:in `call'\", \"/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:638:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:99:in `run_callbacks'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/callbacks.rb:26:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/executor.rb:14:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'\", \"/usr/local/bundle/gems/web-console-4.2.1/lib/web_console/middleware.rb:132:in `call_app'\", \"/usr/local/bundle/gems/web-console-4.2.1/lib/web_console/middleware.rb:19:in `block in call'\", \"/usr/local/bundle/gems/web-console-4.2.1/lib/web_console/middleware.rb:17:in `catch'\", \"/usr/local/bundle/gems/web-console-4.2.1/lib/web_console/middleware.rb:17:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'\", \"/usr/local/bundle/gems/railties-7.0.8/lib/rails/rack/logger.rb:40:in `call_app'\", \"/usr/local/bundle/gems/railties-7.0.8/lib/rails/rack/logger.rb:25:in `block in call'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'\", \"/usr/local/bundle/gems/railties-7.0.8/lib/rails/rack/logger.rb:25:in `call'\", \"/usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/request_id.rb:26:in `call'\", \"/usr/local/bundle/gems/rack-2.2.8/lib/rack/method_override.rb:24:in `call'\", \"/usr/local/bundle/gems/rack-2.2.8/lib/rack/runtime.rb:22:in `call'\", \"/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/server_timing.rb:60:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/executor.rb:14:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/static.rb:23:in `call'\", \"/usr/local/bundle/gems/rack-2.2.8/lib/rack/sendfile.rb:110:in `call'\", \"/usr/local/bundle/gems/actionpack-7.0.8/lib/action_dispatch/middleware/host_authorization.rb:138:in `call'\", \"/usr/local/bundle/gems/railties-7.0.8/lib/rails/engine.rb:530:in `call'\", \"/usr/local/bundle/gems/puma-5.6.7/lib/puma/configuration.rb:252:in `call'\", \"/usr/local/bundle/gems/puma-5.6.7/lib/puma/request.rb:77:in `block in handle_request'\", \"/usr/local/bundle/gems/puma-5.6.7/lib/puma/thread_pool.rb:340:in `with_force_shutdown'\", \"/usr/local/bundle/gems/puma-5.6.7/lib/puma/request.rb:76:in `handle_request'\", \"/usr/local/bundle/gems/puma-5.6.7/lib/puma/server.rb:443:in `process_client'\", \"/usr/local/bundle/gems/puma-5.6.7/lib/puma/thread_pool.rb:147:in `block in spawn_thread'\"]"]]
  ↳ app/controllers/application_controller.rb:54:in `log_error'
  TRANSACTION (1.5ms)  COMMIT
  ↳ app/controllers/application_controller.rb:54:in `log_error'
Completed 500 Internal Server Error in 347ms (Views: 0.1ms | ActiveRecord: 2.2ms | Allocations: 8830)

**Comment by wayneliu0019** [comment]
你使用`script`目录下的all_in_one启动的csghub服务吧？请如果是git server一直是unhealth状态，git server启动日志没有任何明显错误，需要查看下gitlog下的日志，猜测可能是由于文件权限问题，没有执行完初始化脚本，比如还没有创建root用户等等，请尝试进行如下检查和操作：

1. 确保**第一次**启动时候用`startup.sh`脚本启动服务；
2. 将宿主机当前目录下的`gitdata` 和`gitlog`的权限更改为777，即执行`chmod -R gitdata`
3. 如果问题还是存在，将csghub卸载重新安装（git server可能存在db和磁盘文件不一致）
```
docker compose -f docker-compose.yml down -v
rm -rf ./gitdata
rm -rf ./gitlog
```
然后重新执行startup.sh脚本

**Comment by UberIzual** [comment]
> 你使用`script`目录下的all_in_one启动的csghub服务吧？请如果是git server一直是unhealth状态，git server启动日志没有任何明显错误，需要查看下gitlog下的日志，猜测可能是由于文件权限问题，没有执行完初始化脚本，比如还没有创建root用户等等，请尝试进行如下检查和操作：
> 
> 1. 确保**第一次**启动时候用`startup.sh`脚本启动服务；
> 2. 将宿主机当前目录下的`gitdata` 和`gitlog`的权限更改为777，即执行`chmod -R gitdata`
> 3. 如果问题还是存在，将csghub卸载重新安装（git server可能存在db和磁盘文件不一致）
> 
> ```
> docker compose -f docker-compose.yml down -v
> rm -rf ./gitdata
> rm -rf ./gitlog
> ```
> 
> 然后重新执行startup.sh脚本

gitea boot.log 中的报错

2024/06/17 07:48:25 .../setting/security.go:166:loadSecurityFrom() [W] Enabling Query API Auth tokens is not recommended. DISABLE_QUERY_AUTH_TOKEN will default to true in gitea 1.23 and will be removed in gitea 1.24.
2024/06/17 07:48:25 cmd/web.go:242:runWeb() [I] Starting Gitea on PID: 238
2024/06/17 07:48:25 cmd/web.go:111:showWebStartupMessage() [I] Gitea version: 34105e75f built with GNU Make 4.3, go1.21.5 : bindata
2024/06/17 07:48:25 cmd/web.go:112:showWebStartupMessage() [I] * RunMode: prod
2024/06/17 07:48:25 cmd/web.go:113:showWebStartupMessage() [I] * AppPath: /opt/bitnami/gitea/bin/gitea
2024/06/17 07:48:25 cmd/web.go:114:showWebStartupMessage() [I] * WorkPath: /opt/bitnami/gitea
2024/06/17 07:48:25 cmd/web.go:115:showWebStartupMessage() [I] * CustomPath: /opt/bitnami/gitea/custom
2024/06/17 07:48:25 cmd/web.go:116:showWebStartupMessage() [I] * ConfigFile: /opt/bitnami/gitea/custom/conf/app.ini
2024/06/17 07:48:25 cmd/web.go:117:showWebStartupMessage() [I] Prepare to run install page
2024/06/17 07:48:25 cmd/web.go:304:listen() [I] Listen: http://0.0.0.0:3001/gitserver
2024/06/17 07:48:25 cmd/web.go:308:listen() [I] AppURL(ROOT_URL): http://192.168.0.41/gitserver/
2024/06/17 07:48:25 ...s/graceful/server.go:50:NewServer() [I] Starting new Web server: tcp:0.0.0.0:3001 on PID: 238
2024/06/17 07:48:30 ...eful/manager_unix.go:138:handleSignals() [W] PID 238. Received SIGTERM. Shutting down...
2024/06/17 07:48:30 ...eful/server_hooks.go:46:doShutdown() [I] PID: 238 Listener ([::]:3001) closed.
2024/06/17 07:48:30 cmd/web.go:355:listen() [I] HTTP Listener: 0.0.0.0:3001 Closed
2024/06/17 07:48:30 .../graceful/manager.go:168:doHammerTime() [W] Setting Hammer condition
2024/06/17 07:48:31 .../graceful/manager.go:184:doTerminate() [W] Terminating
2024/06/17 07:48:31 cmd/web.go:145:serveInstall() [I] PID: 238 Gitea Web Finished
[no logger writer]: PID: 238. Background context for manager closed - context canceled - Shutting down...

**Comment by Rader** [comment]
close as no response
