### ISSUE TITLE
上传文件时遇到的一系列bug

### ISSUE THREAD

**Issue by heruihr** [OpenCSGs/CSGHub#254]
在自己要上传的文件夹里面
1. git init  ----要初始化
2. git add
3. git remote add origin http://XXXX/XXXX/XXXX/XX.git   ----要传上去的地址 可以在下载按钮里看
4. git config --global user.email “XXXX”
5. git config --global user.name "XXXX"
6. git commit -m "commit message"
7. git push --set-upstream origin main  ----这里要填Username 就是注册的用户名 Password不是密码是用户管理页面的“git token”
8.  如果出现! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'http://XXXX/XXXX/XXXX/XX.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
就打命令git pull origin main --allow-unrelated-histories 将本地没有的文件先跟远程仓库对齐
我用的Linux会出现个修改文件，它已经改好了，直接按ctrl+X退出再回车就保存了，效果如下
Merge made by the 'recursive' strategy.
 .gitattributes | 56 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 README.md      |  5 +++++
 2 files changed, 61 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 README.md
9. 最后再输一遍步骤7就可以啦！累死老子了，下面是上传成功的反馈
Counting objects: 5, done.
Delta compression using up to 104 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 9.30 MiB | 18.70 MiB/s, done.
Total 5 (delta 0), reused 0 (delta 0)
remote: . Processing 1 references
remote: Processed 1 references in total
To http://XXXX/XXXX/XXXX/XX.git
   6da3105..c49990c  main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.

**Comment by hiveer** [comment]
@heruihr 这些操作看起来都是很正常的 Git 操作，没有 bug，不过这个对于其他不太熟悉 Git 的小伙伴来说是个很好的参考，感谢分享！
