### ISSUE TITLE
完整部署文档不存在吗？

### ISSUE THREAD

**Issue by zhouwj83** [OpenCSGs/CSGHub#305]
https://github.com/OpenCSGs/CSGHub/blob/release-v0.7.0/docs/full_deployment_cn.md

**Comment by Rader** [comment]
多谢反馈！
v0.7 版本计划使用k8s 一键部署， helm chart 的脚本很快会更新上来。

**Comment by zhouwj83** [comment]
> 多谢反馈！ v0.7 版本计划使用k8s 一键部署， helm chart 的脚本很快会更新上来。

那请问目前docker镜像 opencsg/**:latest对应的是什么版本？

**Comment by Rader** [comment]
> > 多谢反馈！ v0.7 版本计划使用k8s 一键部署， helm chart 的脚本很快会更新上来。
> 
> 那请问目前docker镜像 opencsg/**:latest对应的是什么版本？

目前还是 v0.6

**Comment by Rader** [comment]
@zhouwj83 镜像已经更新到 v0.7

**Comment by zhouwj83** [comment]
@Rader 已部署最新版本，感谢

**Comment by zhouwj83** [comment]
关闭
