### ISSUE TITLE
数据集标签点击更新没有反应

### ISSUE THREAD

**Issue by zhouwj83** [OpenCSGs/CSGHub#309]
版本：CSGHub-0.7.0
位置：数据集 - 设置 - 数据集标签 勾选标签 点击更新 无反应

查看控制台，未报错且不发起请求动作

**Comment by zhouwj83** [comment]
补充一下，是docker部署的opencsg/**:lastest版本，不确定是否对应v0.7.0

**Comment by Rader** [comment]
@hiveer “不发起请求动作”，意思是客户端美发发起请求

**Comment by Rader** [comment]
@zhouwj83 请问是 all-in-one安装的吗？用的什么操作系统和浏览器？

**Comment by Rader** [comment]
暂时未能复现这个问题。

@zhouwj83 试试创建一个模型，在设置页面修改标签呢？ 最好能把当时操作的页面截个图。

**Comment by zhouwj83** [comment]
@Rader 部署最新的docker镜像包就好了...感谢帮忙查看

**Comment by zhouwj83** [comment]
关闭
