### ISSUE TITLE
拿api测试的时候 token怎么获取

### ISSUE THREAD

**Issue by liminngs** [OpenCSGs/CSGHub#314]
拿api测试的时候 token怎么获取

**Comment by hiveer** [comment]
@liminngs 
<img width="1398" alt="image" src="https://github.com/user-attachments/assets/b845fd32-83e7-43d5-8f59-78b799182adc">

**Comment by miss-uny** [comment]
我的界面只有git token和ssh token， 请问access token为什么没有显示？ 
![image](https://github.com/user-attachments/assets/98e2fde9-d19d-4503-b02b-65c646c808d6)
