### ISSUE TITLE
启动后点击登录抱错

### ISSUE THREAD

**Issue by mengZhongLi** [OpenCSGs/CSGHub#328]
点击登录抱错
![1721369690229](https://github.com/user-attachments/assets/7ba67803-4a9f-41f8-bb6b-026e28f9483b)

**Comment by hiveer** [comment]
@mengZhongLi 请问是通过什么方式部署的？是否更新了环境变量 ON_PREMISE 为 false

**Comment by mengZhongLi** [comment]
通过服务器直接启动的代码，bin/dev,ON_PREMISE没有更新为false，排查时发现.env.development.example在代码中的内容在代码中好像访问不到，STARHUB_BASE_URL配置后重新启动项目也无法找到

**Comment by hiveer** [comment]
> 通过服务器直接启动的代码，bin/dev,ON_PREMISE没有更新为false，排查时发现.env.development.example在代码中的内容在代码中好像访问不到，STARHUB_BASE_URL配置后重新启动项目也无法找到

参考这个文档：https://github.com/OpenCSGs/CSGHub/blob/main/docs/setup.md

你需要新建一个文件：

config/master.key  里面的内容写入： 64f15f995b044427e43fe4897370fd66

**Comment by mengZhongLi** [comment]
![image](https://github.com/user-attachments/assets/067fb3e4-bc2e-4373-a13b-f5a8a09aef4d)
在config下新建master.key已解决问题

**Comment by hiveer** [comment]
> ![image](https://private-user-images.githubusercontent.com/176009930/350316512-067fb3e4-bc2e-4373-a13b-f5a8a09aef4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzcxMjUsIm5iZiI6MTcyMTM3NjgyNSwicGF0aCI6Ii8xNzYwMDk5MzAvMzUwMzE2NTEyLTA2N2ZiM2U0LWJjMmUtNDM3My1hMTNiLWY1YThhMDlhZWY0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwODEzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzE2YjkzODkwY2M4YTg4MWNiZTM2MjBlYzcyOWQwZjlmNTMwYjgyZTg1N2YwN2E3MDA2Y2I2ZDAzZmU4ZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CqPbBS4z-XVcczZDiaB0bdMkjteDRqbvOwDOUuSbNII) 在config下新建master.key已解决问题

谢谢您对社区的贡献，鉴于问题已经解决，我将关闭这个 issue
