### ISSUE TITLE
通过微信登录后，不能生成 Starship API Keys，页面报 "user not found, please login first"

### ISSUE THREAD

**Issue by bbxx111** [OpenCSGs/CSGHub#332]
### 问题描述
1. 使用微信登录 https://opencsg.com/ 。
2. 进入账号设置 -> Starship API Keys ，报 "user not found, please login first" 提示。如下图所示：

<img width="652" alt="25440404132259e2807c2f005c8f366" src="https://github.com/user-attachments/assets/fec25de5-8fa3-40f8-89f2-188f52a4a184">

### 规避方法
需要补充用户名和邮箱之后，退出再重新登录即可避开这个问题。

### 期望结果
微信登录后，直接导引到补充用户名和邮箱的页面补充信息后，再进入主页面。或者自动一个生成用户名，且邮箱可以为空。

**Comment by Rader** [comment]
@bbxx111  最近还有遇到过这样的问题吗？

**Comment by hiveer** [comment]
@bbxx111 问题已修复，请确定且关闭 issue

**Comment by Rader** [comment]
close as no response
