### ISSUE TITLE
bin/dev启动时报错

### ISSUE THREAD

**Issue by zhaoxinhua** [OpenCSGs/CSGHub#339]
我在运行启动开发服务器的时候出现下面的问题，方便的话帮忙看一下，谢谢~

服务器ruby版本：3.2.2
node版本：v22.5.0

![image](https://github.com/user-attachments/assets/9590ff7f-a572-4405-8c0c-44f296cfed27)

**Comment by zhaoxinhua** [comment]
前面执行：sudo yarn install时提示这个，不知道是否有影响

![image](https://github.com/user-attachments/assets/091931b4-4b66-40ee-86ef-b3178c6c9fdd)

**Comment by wayneliu0019** [comment]
这个ms得@hiveer大侠看看！

**Comment by hiveer** [comment]
> 前面执行：sudo yarn install时提示这个，不知道是否有影响
> 
> ![image](https://private-user-images.githubusercontent.com/75721986/350919132-091931b4-4b66-40ee-86ef-b3178c6c9fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTQxNjEsIm5iZiI6MTcyMTcxMzg2MSwicGF0aCI6Ii83NTcyMTk4Ni8zNTA5MTkxMzItMDkxOTMxYjQtNGI2Ni00MGVlLTg2ZWYtYjMxNzhjNmM5ZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA1NTEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYjUxMTQ5NDU4NGZhZDJmMWQ5ZDk0MGQzYjNjNGQ4YmJkODhjZWJlNGYwNDkwMzhlOTA1ZTNhZTExZDYxZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wn7rROpHJUNXNwZ1ngGlDPoc4PfGmbKR_2W3cnlsBE4)

对的，你 yarn install 没有成功呢，所以这个插件没装上，再重新 yarn install 试试

**Comment by Rader** [comment]
close as no response
