### ISSUE TITLE
readme文件中图片的显示

### ISSUE THREAD

**Issue by miss-uny** [OpenCSGs/csghub#341]
readme文件中引入图片 显示是一个图标，我们期望展示的图片本身。

使用下面三种方式，展示的效果都是一个图片图标，而不是图片本身.
![image](https://github.com/user-attachments/assets/35d19444-e132-4797-a087-6618ffc4b28e)

实际效果：
![GitHub Image](/datasets/testaaa/datasetDemo/resolve/main/test/bar.png)
![Alt text](http://git.testaaa.cn/sw/cards/-/blob/main/test/bar.png)
<img src="http://git.testaaa.cn/sw/cards/-/blob/main/test/bar.png"/>

而我们在自己的git库中使用就可以，代码如下
![image](https://github.com/user-attachments/assets/87801abe-5e1f-4ffb-8fa1-ba9ea815cc70)
展示效果如下图
![image](https://github.com/user-attachments/assets/9cc6fe50-3352-40ae-9952-33abf43cf88e)

将图片上传到opencsg的文件夹中

**Comment by miss-uny** [comment]
1. 将文件传入opencsg的文件夹中    2.路径会自动变为![GitHub Image](/datasets/enflame/datasetDemo/resolve/main/1.png) 无法显示

**Comment by Rader** [comment]
@miss-uny 图片默认会使用 lfs，`.gitattributes `里定义了规则
