### ISSUE TITLE
遇到打不开的的文件会直接报错

### ISSUE THREAD

**Issue by mengZhongLi** [OpenCSGs/CSGHub#343]
![image](https://github.com/user-attachments/assets/f1ea714c-9f4b-4cdb-b14f-5d7424d95dda)
这个文件点击后会直接抱错
![image](https://github.com/user-attachments/assets/6fc7f185-7cfd-4667-9ef8-d9c27cadc13b)
文件为：
[model.zip](https://github.com/user-attachments/files/16357666/model.zip)

**Comment by hiveer** [comment]
@mengZhongLi 👍，将在下一个 release 进行增强修复

**Comment by hiveer** [comment]
@mengZhongLi 麻烦提供下你这个 repo 的地址呢，我们确认下是否已经修复

**Comment by Rader** [comment]
close as no response
