### ISSUE TITLE
bin/dev 启动时中断

### ISSUE THREAD

**Issue by zhaoxinhua** [OpenCSGs/CSGHub#346]

**Comment by youngbeom-shin** [comment]
@zhaoxinhua 这个问题我也同样遇到了，解决办法是将 `.env.development`(注意命名) 文件添加到项目跟目录下（和.env.development同一级），之后在命令行中分别键入以下三个命令：
1. bin/rails server -p 3000  
2. bin/rails tailwindcss:watch
3. yarn dev-build
分别用于web、css、js

[env.development.zip](https://github.com/user-attachments/files/16373093/env.development.zip)

**Comment by Rader** [comment]
> @zhaoxinhua 这个问题我也同样遇到了，解决办法是将 `.env.development`(注意命名) 文件添加到项目根目录下（和.env.development同一级），之后在命令行中分别键入以下三个命令：
> 
> 1. bin/rails server -p 3000
> 2. bin/rails tailwindcss:watch
> 3. yarn dev-build
> 
> 分别用于web、css、js
> 
> [env.development.zip](https://github.com/user-attachments/files/16373093/env.development.zip)

@zhaoxinhua 请试试这个方法是否能解决你的问题

**Comment by ganisback** [comment]
duplicate with: https://github.com/OpenCSGs/CSGHub/issues/339
