### ISSUE TITLE
Web 端看不到创建的模型、数据集以及代码仓

### ISSUE THREAD

**Issue by karypi** [OpenCSGs/CSGHub#352]
现象：
可以创建模型并上传文件，如下图：
![image](https://github.com/user-attachments/assets/ca9b5221-fc61-4beb-823f-fbe8f29ef4d8)

但是在模型的 Tab 中看不到任何模型
![image](https://github.com/user-attachments/assets/0855d89b-e476-47ef-abe8-985bce8ff476)

我查看了 portal、server、nginx、minio、gitea 等所有组件的日志都没有发现异常，这个可能是哪个应用的问题？

**Comment by hiveer** [comment]
@karypi 麻烦你打开浏览器的调试，看下是不是有报错

**Comment by karypi** [comment]
![image](https://github.com/user-attachments/assets/dcbab7c3-154c-4de3-8172-61e3089d6672)
调试发现，解析不到 csghub-server，这个是 portal 还是 nginx 的问题？  我在 portal 和 nginx container 中测试都可以解析的。

**Comment by karypi** [comment]
问题已经解决，谢谢
