### ISSUE TITLE
数据集行业标签添加数据后，刷新会出现到数据集标签中

### ISSUE THREAD

**Issue by mengZhongLi** [OpenCSGs/CSGHub#362]
![image](https://github.com/user-attachments/assets/0d903c4b-5c1b-4598-a335-ee210f5eddcd)
![image](https://github.com/user-attachments/assets/0f9e8740-f748-44db-bfc8-6a254089b48d)
模型、数据集都有类似问题

**Comment by Rader** [comment]
行业标签会显示在 **行业** 这个分类下面。看截图，您添加的不是行业标签。
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/dbcbb86b-10ca-4017-9268-7c0ed6555a53">

**Comment by Rader** [comment]
close as not a bug.
