### ISSUE TITLE
csghub-git 容器反复重启

### ISSUE THREAD

**Issue by miss-uny** [OpenCSGs/CSGHub#472]
csghub-git 容器反复重启、每隔几秒就重启一次

相关容器的log：
[csghub-git.log](https://github.com/user-attachments/files/16609074/csghub-git.log)

**Comment by leipeizhao** [comment]
gitea 07:15:01.82 DEBUG ==> Setting server.ROOT_URL to 'http:///gitserver' in Gitea configuration
gitea 07:15:01.82 DEBUG ==> Setting server.SSH_DOMAIN to '/gitserver' in Gitea configuration


你这两个地址配置错误

**Comment by pulltheflower** [comment]
![image](https://github.com/user-attachments/assets/16476721-a264-46d4-a69f-7ff2797876a2)
将输出的 html 代码保存后打开，看到报错信息是 `You are trying to install into an existing Gitea database` ，这表明您已经创建了名为 `gitea` 的数据库，如果已有的 gitea 数据库没有重要信息的话，您可以删除已有的 gitea 数据库并重新启动容器

**Comment by miss-uny** [comment]
> ![image](https://private-user-images.githubusercontent.com/38434877/357748561-16476721-a264-46d4-a69f-7ff2797876a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjY2NDYsIm5iZiI6MTcyMzYyNjM0NiwicGF0aCI6Ii8zODQzNDg3Ny8zNTc3NDg1NjEtMTY0NzY3MjEtYTI2NC00NmQ0LWE2OWYtN2ZmMjc5Nzg3NmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA5MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNDFkZjc1NTVhMWMxYzY5YzhiN2NjMTM5Y2EzNzZjNzE0ZjVhYTcxYjIxYWZlNDU3YjFjYjU1YTA5NDcxY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bs-HjvBF0ieTBhuDMbqjbO8QvamC6cwKhBANpuYAtEo) 将输出的 html 代码保存后打开，看到报错信息是 `You are trying to install into an existing Gitea database` ，这表明您已经创建了名为 `gitea` 的数据库，如果已有的 gitea 数据库没有重要信息的话，您可以删除已有的 gitea 数据库并重新启动容器

数据库中有数据需要导出，请问如何导，导出来是可以删除的

**Comment by miss-uny** [comment]
> gitea 07:15:01.82 DEBUG ==> Setting server.ROOT_URL to 'http:///gitserver' in Gitea configuration gitea 07:15:01.82 DEBUG ==> Setting server.SSH_DOMAIN to '/gitserver' in Gitea configuration
> 
> 你这两个地址配置错误
看起来是 server_domain这个参数 没有解析

**Comment by pulltheflower** [comment]
@miss-uny 进入 postgres 的容器内部，执行 

```shell
 pg_dump -U postgres gitea > gitea.pgsql
```

**Comment by miss-uny** [comment]
> ```shell
> pg_dump -U postgres gitea > gitea.pgsql
> ```

导入和删除，分别如何操作

**Comment by pulltheflower** [comment]
@miss-uny 进入 postgres 的 docker 容器首先导出数据

```shell
 pg_dump -U postgres gitea > gitea.pgsql
```

然后删除数据库
```shell
psql -U postgres
DROP DATABASE gitea;
```

然后重新创建数据库，并导入数据
```shell
CREATE DATABASE gitea;
\q
```

最后重新导入数据
```shell
psql -U postgres gitea < gitea.pgsql
```

**Comment by miss-uny** [comment]
数据库删除后，再次启动，问题仍然存在
log为： [csghub-git1.log](https://github.com/user-attachments/files/16620388/csghub-git1.log)

html报错

**Comment by pulltheflower** [comment]
@miss-uny 数据库删除后您有没有重新创建新的 gitea 数据库并导入数据？看报错的 html 显示找不到数据库
<img width="1177" alt="image" src="https://github.com/user-attachments/assets/121d2530-edfb-4da4-aa9b-a6538c8e99ba">

**Comment by miss-uny** [comment]
操作流程为：
1. 进入 postgres 的 docker 容器首先导出数据
2. 删除数据库 gitea
3. 创建数据库gitea，保存
4. docker compose -f all-in-one.yml down
5. docker compose -f all-in-one.yml up -d
6. 进入postgres 的 docker 容器， 导入数据
7.  登录opencsg界面，成功
8. 点击
9. 
跳转后报错
![Uploading image.png…]()

**Comment by pulltheflower** [comment]
@miss-uny 看报错信息来看是在 gitea 中不存在 admin001 这个用户，请登录 gitea 后台并使用 admin001 查看是否可以登录成功

**Comment by miss-uny** [comment]
问题解答汇总：
A.地址配置错误，报错如下：
gitea 07:15:01.82 DEBUG ==> Setting server.ROOT_URL to 'http:///gitserver' in Gitea configuration
gitea 07:15:01.82 DEBUG ==> Setting server.SSH_DOMAIN to '/gitserver' in Gitea configuration
解决：
需要在启动容器前执行
export SERVER_DOMAIN=**.**.**.**


B. gitea未将数据导入到本地磁盘存储
导致容器重启后，需要先备份再清理

修复：
a）all-in-one.yml 中gitea增加 以下部分
volumes:
    - ./data/gitea:/bitnami/gitea
 chmod -R 777 data（将data目录赋予权限777）
b）重启
1.进入 postgres 的 docker 容器首先导出数据
pg_dump -U postgres gitea > gitea.pgsql
 
 
2.删除数据库 gitea
psql -U postgres
DROP DATABASE gitea;
创建数据库gitea，保存
CREATE DATABASE gitea;\q
 
 
3.再次启动
docker compose -f all-in-one.yml up -d
进入postgres 的 docker 容器， 导入数据
psql -U postgres gitea < gitea.pgsql

c）1进入 csghub-server的 docker 容器，修复gitea的组织数据
./starhub trigger fix-org-data

d)登录gitea的后台
http://**.**.**.**/gitserver
创建账号admin001、组织（datasets_admin001,modals_admin001等）

e)再次重启容器验证，是否正常

**Comment by pulltheflower** [comment]
问题已解决，关闭此 issue。
