### ISSUE TITLE
代码仓库按License过滤，数据结果为空

### ISSUE THREAD

**Issue by leipeizhao** [OpenCSGs/csghub#518]
简单排查后发现是repository_tags没有数据，导致join后没有数据，版本0.7.0

**Comment by ganisback** [comment]
Thanks for raising issue, we will fix it as soon as possible

**Comment by Rader** [comment]
@leipeizhao 尝试再修改下 README.md ，看看 license 的 tag 能否在代码仓库的详情页面正常显示？
