### ISSUE TITLE
当模型、数据集、代码库同名时，修改标签失败

### ISSUE THREAD

**Issue by leipeizhao** [OpenCSGs/CSGHub#526]
存在同名的repo时，git的回调函数中似乎没有判断repo的类型，导致标签更新其他的同名的数据上

**Comment by zhendi** [comment]
@leipeizhao 您好，可以具体描述下复现步骤吗？

**Comment by leipeizhao** [comment]
> @leipeizhao 您好，可以具体描述下复现步骤吗？

1 创建一个名称叫test的代码库
2 创建一个名称叫test的数据集
3 在test数据集的设置中修改标签为“文本分类”
4 刷新查看test数据集 并没有标签，标签在test的代码库上

**Comment by hiveer** [comment]
> > @leipeizhao 您好，可以具体描述下复现步骤吗？
> 
> 1 创建一个名称叫test的代码库 2 创建一个名称叫test的数据集 3 在test数据集的设置中修改标签为“文本分类” 4 刷新查看test数据集 并没有标签，标签在test的代码库上

你说的不是代码库吧？我们目前只有模型和数据集支持任务标签

**Comment by leipeizhao** [comment]
> > > @leipeizhao您好，可以具体描述下复现步骤吗？
> > 
> > 
> > 1 创建一个名为测试的代码库 2 创建一个名为测试的数据集 3 在测试数据集的设置中修改标签为“文本分类” 4 刷新查看测试数据集并没有标签，标签在测试的代码库上
> 
> 你说的不是代码库吧？我们目前只有模型和数据集支持任务标签

![截图_选择区域_20240823153406](https://github.com/user-attachments/assets/ded9dac9-04db-4dbe-b14f-862983c42e62)
如图  ，应该时builder\store\database\tag.go 中SetMetaTags方法里面Where("path =?", fmt.Sprintf("%v/%v", namespace, name))应该加上repository_type 条件

**Comment by Rader** [comment]
@leipeizhao  确实是一个 bug，需要从 csghub-server 端来fix

感谢指出！
