### ISSUE TITLE
all-in-one 打不开，helm 打不开

### ISSUE THREAD

**Issue by karypi** [OpenCSGs/CSGHub#531]
https://github.com/OpenCSGs/CSGHub/blob/release-v0.8.0/deploy/all_in_one/README.md  文档里的 https://github.com/OpenCSGs/CSGHub-helm 找不到

v0.7 里的 all-in-one 找不到  https://github.com/OpenCSGs/CSGHub/tree/release-v0.7.0?tab=readme-ov-file#quick-start
curl -L https://raw.githubusercontent.com/OpenCSGs/csghub/main/all-in-one-CN.yml -o all-in-one-CN.yml

**Comment by Rader** [comment]
@karypi 推荐直接使用 v0.8.0 的安装脚本

https://github.com/OpenCSGs/CSGHub-helm  已经公开访问
