### ISSUE TITLE
gitea 持久化到本地大约会占用多少空间？

### ISSUE THREAD

**Issue by karypi** [OpenCSGs/CSGHub#532]
gitea 都储存哪些数据？ 想了解下大概的占用空间。

![image](https://github.com/user-attachments/assets/22c9c8e6-2343-47d4-8cc0-9cf187084c4f)

**Comment by karypi** [comment]
另外 gitlog 是必须的吗？
![image](https://github.com/user-attachments/assets/0619df29-c508-4eb7-96fb-174c27773406)

**Comment by Rader** [comment]
gitea 的目录主要存储 模型、数据集等的git 仓库文件，多大空间决定于存放的 模型和数据集的大小

> gitea 都储存哪些数据？ 想了解下大概的占用空间。
> 
> ![image](https://private-user-images.githubusercontent.com/37999635/361365130-22c9c8e6-2343-47d4-8cc0-9cf187084c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Nzg1NDksIm5iZiI6MTcyNDY3ODI0OSwicGF0aCI6Ii8zNzk5OTYzNS8zNjEzNjUxMzAtMjJjOWM4ZTYtMjM0My00N2Q0LThjYzAtOWNmMTg3MDg0YzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEzMTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMjA3MTk5OGQwZmEyNjY0NDgxM2IwMTllN2JmNGNmMzc4M2Y2YmZhYmFlYzFkYjFkMzNiN2Q3Mzc0ZGJiOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yIbXk36-qcZsEtubxuYxlbp6YlWsC_XmXh0tPDOXds8)

**Comment by Rader** [comment]
gitlog 占用不了多少空间，最好保留，方便诊断问题

> 另外 gitlog 是必须的吗？ ![image](https://private-user-images.githubusercontent.com/37999635/361368986-0619df29-c508-4eb7-96fb-174c27773406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Nzg1NDksIm5iZiI6MTcyNDY3ODI0OSwicGF0aCI6Ii8zNzk5OTYzNS8zNjEzNjg5ODYtMDYxOWRmMjktYzUwOC00ZWI3LTk2ZmItMTc0YzI3NzczNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEzMTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYTFhZTMzMDc4ODkzN2U3MDhlNzBjY2FlNGMzN2Y1YzdmNjk4ODk1ODU5NjE5MDE4ZmRkMmI3M2ZiMmRkNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TSDOFHIGPIHoaxD02h3ncaQfjYGQpNEIzTC-YWOuOLY)

**Comment by ganisback** [comment]
close it, if you have any questions, please open a new one
