### ISSUE TITLE
按照官网文档一键部署之后，点击系统一级菜单获取不到数据，注册完成之后登录报错

### ISSUE THREAD

**Issue by wangyanna13** [OpenCSGs/CSGHub#543]
问题一：点击系统任意一级菜单都报错“获取不到数据”，见下图
[
![访问菜单报错](https://github.com/user-attachments/assets/4699dd51-d70d-4046-a810-63e2e9582f78)
](url)

问题二：注册完成登录报错如下
An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.

**Comment by wangyanna13** [comment]
问题一：点击系统任意一级菜单都报错“获取不到数据”，见下图

访问菜单报错

问题二：注册完成登录报错如下
An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.

**Comment by wayneliu0019** [comment]
注册登录没问题。但访问任何菜单包凑。

猜测可能后端服务有报错。

麻烦贴下portal的日志看看，位于安装目录的`log/`文件夹下；另外也贴下在出现错误时候，后端starhub_server服务的日志。

**Comment by SeanHH86** [comment]
第一次安装后，有添加过 model, dataset, space吗？可以查询一下数据库中是否有数据。

**Comment by wangyanna13** [comment]
一、如果登录没有问题，登录不进去，无法操作后续，比如 无法添加model, dataset, space，portal日志如下：
![potal报错](https://github.com/user-attachments/assets/83cc9f92-07b6-4207-b6d8-ab7ed0b5bde3)

二、看portal日志显示网络问题，项目路径config/environments修改配置文件development.rb，开放网络如下，仍然还是之前的错误：
![网络配置](https://github.com/user-attachments/assets/6a33c86b-6b7e-4169-8463-19ffdf2e8b34)

**Comment by SeanHH86** [comment]
在部署前后，有对哪些配置项做过变更吗？另外csghub server这个服务日志中有报错信息吗？

**Comment by hiveer** [comment]
@wangyanna13 
麻烦提供两个信息：
1. 打开浏览器的调试，查看 XHR 的请求：
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/96c6ebd4-7b97-43fb-b1c7-31d6ae73e020">
2. 然后查看日志，是否有报错信息

**Comment by wangyanna13** [comment]
一、一直报网络问题，就改了此配置docker-compose.yml网络相关（networks）的配置，以及development.rb配置中开放网络的配置，这些需要是否需要修改？

二、csghub server日志如下：
![Uploading server日志.png…]()

**Comment by wangyanna13** [comment]
浏览器报错如下：
![浏览器报错](https://github.com/user-attachments/assets/9d9ee539-d688-4d5e-8695-3941e359937f)

**Comment by wangyanna13** [comment]
浏览器报错如下：
![浏览器报错](https://github.com/user-attachments/assets/bb75f144-d9d0-414f-8d3a-1294c9e5b90c)

**Comment by wangyanna13** [comment]
源码下载的是main分支，启动起来一共16个服务，有五个貌似有问题，是16个都要启动起来么？另外5个启动不起来
![服务报错](https://github.com/user-attachments/assets/b10d6ccd-61a8-4b39-ac6c-0c59c593b697)

**Comment by wangyanna13** [comment]
要启动这两个服务，需要修改哪些配置？或者需要提前安装什么软件么，目前除了改了网络的配置，别的配置都没有改，这两个服务都有问题，没有启动成功

**Comment by SeanHH86** [comment]
使用
docker logs gitea_1 -f 
和
docker logs user_server_1 -f
这两条命令分别看一下container的启动log, 看看报错信息，也可以上传到这里。

**Comment by wangyanna13** [comment]
gitea如下：
![gitea日志](https://github.com/user-attachments/assets/ed80fc9d-0a83-4012-be4b-9314e5b9d755)


user_server如下：
![user](https://github.com/user-attachments/assets/3518b7e3-dbf8-41b8-8228-ada6735d1112)

**Comment by SeanHH86** [comment]
Gitea container把目录权限mount到/opt/bitnami/gitea的目录给上755权限。
Use server应该是由于gitea没有连上而初始化access token失败导致的。

**Comment by wangyanna13** [comment]
一、Gitea服务正常了，Use server依然报错，如下：
![user报错](https://github.com/user-attachments/assets/f62acd8c-03f4-4d56-ad01-e844e63a03b7)


二、redis-1和csghub_server_runner-1这两个容器也必须要启动么？这两个也没有启动成功

**Comment by SeanHH86** [comment]
查询一下数据库中是否有表git_server_access_tokens。

**Comment by wangyanna13** [comment]
user_server需要重启一下，问题已经解决
