### ISSUE TITLE
组织成员登录后无法在首页数据集列表 内查看数据集

### ISSUE THREAD

**Issue by miss-uny** [OpenCSGs/CSGHub#571]
1.使用管理员admin,创建组织test，并在test组织内上传dataset
2.注册用户public， 并以只读身份加入组织test
3.使用public登录后，数据集列表为空
3.点击个人信息-》组织机构 -》组织名test，才能在数据集列表中看到数据集。
请帮忙确认流程是否正常。期望登录后 即可查看

**Comment by SeanHH86** [comment]
感谢指出问题，正在检查行为。
