### ISSUE TITLE
界面提示“加载数据报错”数据集列表不显示，数据集数量为0（暂未上传模型，无法验证）

### ISSUE THREAD

**Issue by miss-uny** [OpenCSGs/csghub#580]
如题
1.界面提示“加载数据报错”后，数据集列表不显示，数据集数量为0（暂未上传模型，无法验证）           
2. 重新登录后问题消失

**Comment by Rader** [comment]
出现这个错误可能是当时请求后端服务 starhub_server 的 api 报错了。
请提供一下当时浏览器的请求的响应信息，从浏览器的开发者工具里能看到网络请求。

**Comment by Rader** [comment]
可以 docker ps查看一下服务状态，有没有正常启动。
docker logs 看看是否有错误日志

**Comment by Rader** [comment]
close as no response
