### ISSUE TITLE
运行后获取数据集失败以及无法登录

### ISSUE THREAD

**Issue by kyrieirvingcsgo** [OpenCSGs/csghub#592]
![image](https://github.com/user-attachments/assets/b469b6a8-34c8-4498-9be3-54a200984e07)
![image](https://github.com/user-attachments/assets/e1478918-7f19-426d-9f00-44623024068c)

使用了all-in-one目录启动

![image](https://github.com/user-attachments/assets/3b295da2-8ed5-462e-953d-f92bdf3ddfb8)

**Comment by kyrieirvingcsgo** [comment]
![image](https://github.com/user-attachments/assets/628c1408-4eb5-4b5c-b422-b256c4294d5a)
数据集请求失败的网络请求

**Comment by Rader** [comment]
从 docker ps的输出看，csghub-server 服务端的服务一直再重启，应该有错误。可以发一下服务日志，方便分析

**Comment by kyrieirvingcsgo** [comment]
> 从 docker ps的输出看，csghub-server 服务端的服务一直再重启，应该有错误。可以发一下服务日志，方便分析

Starting periodic command scheduler: cron.
Done.
Database setup...
Migration init
init logger, level: INFO, format: json
Migration migrate
init logger, level: INFO, format: json
{"time":"2024-09-11T03:58:30.377603992Z","level":"INFO","msg":"there are no new migrations to run (database is up to date)"}
Start server...
init logger, level: INFO, format: json
{"time":"2024-09-11T03:58:30.57101418Z","level":"INFO","msg":"FIFOScheduler run started"}
{"time":"2024-09-11T03:58:30.583845226Z","level":"ERROR","msg":"refresh status all failed","error":"Get \"http://csghub_server_runner:8082/api/v1/service/status-all\": dial tcp: lookup csghub_server_runner on 127.0.0.11:53: server misbehaving"}
{"time":"2024-09-11T03:58:30.584350679Z","level":"ERROR","msg":"Error sending request:","!BADKEY":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T03:58:30.584488554Z","level":"ERROR","msg":"Fail to create git server access token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T03:58:30.584549616Z","level":"ERROR","msg":"Failed to find or create token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T03:58:30.584659808Z","level":"ERROR","msg":"fail to create git server,error:Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
Error: failed to init router: error creating git http handler:fail to create git server,error:Post "http://gitea:3001/api/v1/users/root/tokens": dial tcp 172.25.0.2:3001: connect: connection refused
Gitea log scan job already exists
Calculate score job already exists
Create push mirror job already exists
Check mirror progress job already exists
Sync as client job already exists
Restarting periodic command scheduler: cronStopping periodic command scheduler: cron.
Starting periodic command scheduler: cron.
Done.
Database setup...
Migration init
init logger, level: INFO, format: json
Migration migrate
init logger, level: INFO, format: json
{"time":"2024-09-11T03:59:31.022165305Z","level":"INFO","msg":"there are no new migrations to run (database is up to date)"}
Start server...
init logger, level: INFO, format: json
{"time":"2024-09-11T03:59:31.229772559Z","level":"INFO","msg":"FIFOScheduler run started"}
{"time":"2024-09-11T03:59:31.232867129Z","level":"ERROR","msg":"Error sending request:","!BADKEY":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T03:59:31.232903623Z","level":"ERROR","msg":"Fail to create git server access token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T03:59:31.233630127Z","level":"ERROR","msg":"Failed to find or create token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T03:59:31.233688264Z","level":"ERROR","msg":"fail to create git server,error:Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
Error: failed to init router: error creating git http handler:fail to create git server,error:Post "http://gitea:3001/api/v1/users/root/tokens": dial tcp 172.25.0.2:3001: connect: connection refused
root@hcss-ecs-c9de:/csghub/CSGHub-main/deploy/all_in_one# 


---------------------------------------------------
{"time":"2024-09-11T03:58:59.156250952Z","level":"ERROR","msg":"Error sending request:","!BADKEY":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T03:58:59.156508093Z","level":"ERROR","msg":"Fail to create git server access token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T03:58:59.15655508Z","level":"ERROR","msg":"Failed to find or create token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
Error: failed to init router: error creating user handler:failed to create user component: failed to create git server,error:Post "http://gitea:3001/api/v1/users/root/tokens": dial tcp 172.25.0.2:3001: connect: connection refused
init logger, level: INFO, format: json
{"time":"2024-09-11T03:59:59.474378627Z","level":"ERROR","msg":"Error sending request:","!BADKEY":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T03:59:59.474552248Z","level":"ERROR","msg":"Fail to create git server access token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T03:59:59.474571502Z","level":"ERROR","msg":"Failed to find or create token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
Error: failed to init router: error creating user handler:failed to create user component: failed to create git server,error:Post "http://gitea:3001/api/v1/users/root/tokens": dial tcp 172.25.0.2:3001: connect: connection refused
init logger, level: INFO, format: json
{"time":"2024-09-11T04:01:00.163978149Z","level":"ERROR","msg":"Error sending request:","!BADKEY":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T04:01:00.164102838Z","level":"ERROR","msg":"Fail to create git server access token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T04:01:00.164111616Z","level":"ERROR","msg":"Failed to find or create token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
Error: failed to init router: error creating user handler:failed to create user component: failed to create git server,error:Post "http://gitea:3001/api/v1/users/root/tokens": dial tcp 172.25.0.2:3001: connect: connection refused
-------------------------------------------------------------------------------------------------------------------------------
这是nginx服务的
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] server name "*." is invalid in /etc/nginx/nginx.conf:208
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] server name "*." is invalid in /etc/nginx/nginx.conf:208

**Comment by kyrieirvingcsgo** [comment]
**all_in_one_user_server_1**
```
/{"time":"2024-09-11T06:43:23.610126193Z","level":"ERROR","msg":"Error sending request:","!BADKEY":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T06:43:23.610247671Z","level":"ERROR","msg":"Fail to create git server access token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T06:43:23.610257334Z","level":"ERROR","msg":"Failed to find or create token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
Error: failed to init router: error creating user handler:failed to create user component: failed to create git server,error:Post "http://gitea:3001/api/v1/users/root/tokens": dial tcp 172.25.0.2:3001: connect: connection refused
```

------------------------------------------------
**all_in_one_csghub_server_1**
```
Error: failed to init router: error creating git http handler:fail to create git server,error:Post "http://gitea:3001/api/v1/users/root/tokens": dial tcp 172.25.0.2:3001: connect: connection refused
Gitea log scan job already exists
Calculate score job already exists
Create push mirror job already exists
Check mirror progress job already exists
Sync as client job already exists
Restarting periodic command scheduler: cronStopping periodic command scheduler: cron.
Starting periodic command scheduler: cron.
Done.
Database setup...
Migration init
init logger, level: INFO, format: json
Migration migrate
init logger, level: INFO, format: json
{"time":"2024-09-11T06:45:30.712015165Z","level":"INFO","msg":"there are no new migrations to run (database is up to date)"}
Start server...
init logger, level: INFO, format: json
{"time":"2024-09-11T06:45:30.897340101Z","level":"INFO","msg":"FIFOScheduler run started"}
{"time":"2024-09-11T06:45:30.900772126Z","level":"ERROR","msg":"Error sending request:","!BADKEY":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T06:45:30.900826286Z","level":"ERROR","msg":"Fail to create git server access token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T06:45:30.900833417Z","level":"ERROR","msg":"Failed to find or create token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T06:45:30.900859376Z","level":"ERROR","msg":"fail to create git server,error:Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
Error: failed to init router: error creating git http handler:fail to create git server,error:Post "http://gitea:3001/api/v1/users/root/tokens": dial tcp 172.25.0.2:3001: connect: connection refused
```
-----------------------------------------------
**all_in_one_server_proxy_nginx_1**
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] invalid port in upstream "_CSGHUB_KNATIVE_GATEWAY_HOST:_CSGHUB_KNATIVE_GATEWAY_PORT" in /etc/nginx/nginx.conf:88
```
-------------------------------------------------
**all_in_one_nginx_1**

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] server name "*." is invalid in /etc/nginx/nginx.conf:208
```
----------------------------------
 **all_in_one_csghub_server_proxy_1**

```
init logger, level: INFO, format: json
{"time":"2024-09-11T06:52:24.929692372Z","level":"ERROR","msg":"Error sending request:","!BADKEY":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T06:52:24.929804061Z","level":"ERROR","msg":"Fail to create git server access token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T06:52:24.929810988Z","level":"ERROR","msg":"Failed to find or create token","error: ":"Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
{"time":"2024-09-11T06:52:24.931231405Z","level":"ERROR","msg":"fail to create git server,error:Post \"http://gitea:3001/api/v1/users/root/tokens\": dial tcp 172.25.0.2:3001: connect: connection refused"}
Error: failed to init router: error creating rproxy handler:failed to create space component,fail to create git server,error:Post "http://gitea:3001/api/v1/users/root/tokens": dial tcp 172.25.0.2:3001: connect: connection refused
```

---------------------------------
**all_in_one_csghub_server_runner_1**
```
{"time":"2024-09-11T06:52:25.217314592Z","level":"ERROR","msg":"falied to build kubeconfig","error":"invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}
Error: failed to build NewHttpServer,failed to build kubeconfig,invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
init logger, level: INFO, format: json
{"time":"2024-09-11T06:53:25.521554669Z","level":"ERROR","msg":"falied to build kubeconfig","error":"invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}
Error: failed to build NewHttpServer,failed to build kubeconfig,invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

```

**Comment by kyrieirvingcsgo** [comment]
> 试试 curl http://172.25.0.2:3001 端口是否通？确认下 gitea 服务是否正常启动了。
> 
> 再检查一下 gitea 的日志，在启动的当前目录下： data/gitea/data/logs/gitea.log 看看是否有错误
你好，这个连接失败了
![image](https://github.com/user-attachments/assets/b8337496-c440-499f-bcc8-b4af1b96594c)

并没有找到您说所的那个目录下的gitea.log

但是其他地方很多
![image](https://github.com/user-attachments/assets/2d776d18-686c-4883-bd6d-a33d88be2a0f)

**Comment by kyrieirvingcsgo** [comment]
@Rader 大佬，从以上给出的信息可以看得出问题吗

**Comment by kyrieirvingcsgo** [comment]
....

**Comment by Rader** [comment]
close as the problem has been solved with tech support from opencsg.com
