### ISSUE TITLE
模型新增tag，提示成功，但实际并没有增加上

### ISSUE THREAD

**Issue by miss-uny** [OpenCSGs/CSGHub#596]
1. testmodel 模型-》设置
2. 模型标签，输入文本生成标签（已有），点击更新，提示更新成功
3 点击模型-》讨论，再点击模型-》设置。 模型标签中并没有已设置的标签

补充，部分模型如此。 
可稳定复现

**Comment by Rader** [comment]
输入 tag 信息之后，是不是弹出了 tag 列表，并从中选择了一个？

**Comment by miss-uny** [comment]
输入tag信息后，是从tag列表钟选择了一个，然后点击更新，提示”更新成功“

**Comment by Rader** [comment]
模型详情页的顶部有之前输入的 tag 了吗？
<img width="756" alt="image" src="https://github.com/user-attachments/assets/91ea7fd2-6bee-4678-b465-65e185c26bff">

**Comment by miss-uny** [comment]
在顶部已经有输入的tag了 . 数据集也偶现这个问题，
数据集更新了tag后，顶部查看是有的。并且再次查看数据集标签也是有的testtag，但使用testtag过滤数据集，返回为空

**Comment by Rader** [comment]
方便发一下数据库里 testtag 的详细信息吗？

**Comment by miss-uny** [comment]
1.我没有访问数据库的权限
2.我尝试通过修改markdown 可以解决这个问题
