### ISSUE TITLE
Uploading one data set works fine, pushing multiple data sets will not be visible

### ISSUE THREAD

**Issue by HuangLuGuang** [OpenCSGs/csghub#669]
<img width="2197" alt="image" src="https://github.com/user-attachments/assets/95b9f73f-6f7a-4825-a34e-884cd889b932">
<img width="1770" alt="image" src="https://github.com/user-attachments/assets/7f6e9c58-aeea-4902-a5ae-07dc9f48d0ba">

Each file is about 800M, CSV format

**Comment by ganisback** [comment]
@HuangLuGuang can you help update the title to english? We have some foreign contributors who will look at this issue

**Comment by Rader** [comment]
how many files in this dataset?

**Comment by HuangLuGuang** [comment]
About 50 files, each about 800MB, CSV file

**Comment by HuangLuGuang** [comment]
> how many files in this dataset?


About 50 files, each about 800MB, CSV file

**Comment by Rader** [comment]
could you help list the hareware info like CPU, MEM?

**Comment by HuangLuGuang** [comment]
> could you help list the hareware info like CPU, MEM?
> 
> and, which version of csghub used?

CPU info 
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         43 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
    CPU family:          6
    Model:               63

MEM: 8G

csghub version is latest

**Comment by Rader** [comment]
@HuangLuGuang issue is closed, did you find the root cause?

**Comment by HuangLuGuang** [comment]
> @HuangLuGuang issue is closed, did you find the root cause?

csv files are not tracked by lfs by default，dataset tree api response time is too long.

**Comment by Rader** [comment]
> > @HuangLuGuang issue is closed, did you find the root cause?
> 
> csv files are not tracked by lfs by default，dataset tree api response time is too long.

get it, thanks!
