### ISSUE TITLE
register user error

### ISSUE THREAD

**Issue by leipeizhao** [OpenCSGs/csghub#694]
**Describe the bug**
register user error

**Environment**
CSGHub Version: v0.9
OS: Linux 
Hardware:  4c8G 
Launch:  docker compose 

**To Reproduce**
1. register user test1，login user  is ok，logout test1
2. register user test2，login error，error message is：ERROR: duplicate key value violates unique constraint "users_email_key"
3. because the email info is lost in the function "createFromCasdoorUser" in the project csghub-server

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Rader** [comment]
this bug will be fixed in `v0.9.3`
