### ISSUE TITLE
Suspicious Spike in Star Count

### ISSUE THREAD

**Issue by mintloft** [OpenCSGs/csghub#709]
Hey,

Just wanted to point out something odd I've noticed. Your project has suddenly gotten a huge number of new stars, but a lot of them seem to be from fake or bot accounts with junk content. This looks like artificial star boosting, which isn't really fair play.

Stuff like this skews the perception of genuine interest and kinda undermines the trust in our community. As a fellow researcher and long-time GitHub user, it's pretty disappointing to see this happening. It's a bummer when tactics like these are used, makes it tough for everyone working hard on their projects.

I've reported this to GitHub support and the community for review. Hope you can address this and keep things legit.

Cheers,

**Comment by samchen8008** [comment]
Hi there,
First of all, we are surprised to hear those information from you. Recently, we do notice there are some stars increased, but we did not notice that those stars are suspicious person. 
Plus, could you point out which stars are the stars you mentioned.
We are positive to work with you to figure it out what’s happening here. We do want to collaborate with you guys to avoid unfair stuff in our community.

Also, we are happy to jump in call with you guys for this explanation.

Regards,
Sam Chen 






Alimail------------------------------------------------------------------
***@***.***>
Date:2024/10/11 14:43:08
***@***.***>
***@***.***>
Theme:[OpenCSGs/csghub] Suspicious Spike in Star Count (Issue #709)

Hey,
Just wanted to point out something odd I've noticed. Your project has suddenly gotten a huge number of new stars, but a lot of them seem to be from fake or bot accounts with junk content. This looks like artificial star boosting, which isn't really fair play.
Stuff like this skews the perception of genuine interest and kinda undermines the trust in our community. As a fellow researcher and long-time GitHub user, it's pretty disappointing to see this happening. It's a bummer when tactics like these are used, makes it tough for everyone working hard on their projects.
I've reported this to GitHub support and the community for review. Hope you can address this and keep things legit.
Cheers,
