### ISSUE TITLE
Suspicious Increase in Stars on This Repository

### ISSUE THREAD

**Issue by peahd** [OpenCSGs/csghub#711]
I have noticed unusual activity on your repository recently. In the past three days, there is a sudden notable increase in GitHub Stars. Many of these stars come from accounts that appear to be bots or fake users. Their profiles are filled with irrelevant or spam content. This is very suspicious.

As a long-time GitHub lover and AI researcher, I am truly concerned about this behavior. Artificially boosting stars is against GitHub policies and harms the integrity of the community. It is important that all users follow the rules and maintain fairness.

I kindly ask you to address this issue and stop any activities that violate GitHub guidelines. I have already REPORTED this matter to the GitHub official team and the community moderators for further investigation.

Hope this helps!

**Comment by samchen8008** [comment]
Guys, what's your guys suggestions on current situation? It's new to us and it's hard to reject stars on our side.

**Comment by Rader** [comment]
there is no huge star increase "In the past three days" you mentioned.

Check the project star history:  https://star-history.com/#OpenCSGs/csghub&Date

<img width="870" alt="image" src="https://github.com/user-attachments/assets/44ab79cc-7b37-4ff4-a874-3e24deda0fa5">

**Comment by peahd** [comment]
> Guys, what's your guys suggestions on current situation? It's new to us and it's hard to reject stars on our side.

@samchen8008 @Rader 

Alright, let's cut to the chase. If you guys bought these fake stars, please stop. GitHub won't like it and might punish you, just like they did with GuijiAI from your country.

You can actually REJECT these stars. Don't fall for the fake hype. Just BLOCK 'em -- GitHub's got a how-to doc right here: https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization#blocking-a-user-in-the-organization-settings

Getting ~3k stars in 6 months is great! You're doing well. That's why you should protect your reputation, not use tricks to boost it.

Also, your contributor list is looking pretty in-house. Try inviting more outside contributors. It'll help your project grow in the long run.

Hope you'll think about this. Keep it real, guys. Your project looks promising -- let it succeed on its own merits.
