### ISSUE TITLE
使用 Helm 快速安装

### ISSUE THREAD

**Issue by karypi** [OpenCSGs/csghub#712]
curl -sfL https://raw.githubusercontent.com/OpenCSGs/csghub-installer/refs/heads/main/helm-chart/install.sh | bash -s -- <domain>

当我在我的 k8s 集群中执行时报错：
W1012 14:28:51.972853 2108534 loader.go:222] Config not found: /etc/rancher/k3s/k3s.yaml
E1012 14:28:51.973546 2108534 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1012 14:28:51.973958 2108534 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1012 14:28:51.975442 2108534 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1012 14:28:51.976834 2108534 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1012 14:28:51.978164 2108534 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[2024-10-12 14:28:51] [WARN] K3S cluster is not ready yet. Attempt 10/10.
[2024-10-12 14:29:01] [ERRO] K3S cluster is not up after 10 attempts.
[2024-10-12 14:29:01] [ERRO] Failed to verify K3S cluster status.

是基于 K3S cluster 的吗？  常规的 kubeadm 部署的 k8s 集群需要按照手动部署吗？

**Comment by Rader** [comment]
Please open issue in English, thanks!

Close this issue.
