### ISSUE TITLE
Download AIWizards/bert-base-uncased fail

### ISSUE THREAD

**Issue by lixjohn** [OpenCSGs/csghub#769]
**Describe the bug**
Download AIWizards/bert-base-uncased fail

**Environment**
https://opencsg.com/

**To Reproduce**
1. Go to 'https://opencsg.com/models/AIWizards/bert-base-uncased/files/main/'
2. Click on 'Download Model' button
3. copy git command and run.
      _git lfs install
      git clone https://opencsg.com/models/AIWizards/bert-base-uncased.git_

Download fail with follow error, please see attachment 
[error download.txt](https://github.com/user-attachments/files/17691861/error.download.txt)

Not all files downlaoded, please see snapshot
<img width="255" alt="image" src="https://github.com/user-attachments/assets/39eedac4-7364-4036-9068-c239646b9053">

**Comment by lixjohn** [comment]
BTW - tried download model.safetensors via downlaod button, 
![image](https://github.com/user-attachments/assets/7fd4012d-dd4c-4847-b79a-404e0fe48b49)

go to error page.
<img width="773" alt="image" src="https://github.com/user-attachments/assets/ae741bbc-13b5-49d0-98e0-4c58f6be2a0a">

**Comment by pulltheflower** [comment]
Thanks for reporting this problem, the repo https://opencsg.com/models/AIWizards/bert-base-uncased has been updated and the lfs files have been uploaded.

**Comment by lixjohn** [comment]
Thanks, it works. close this issue.
