### ISSUE TITLE
CSGHub是否支持Xinference大模型下载

### ISSUE THREAD

**Issue by mushixun** [OpenCSGs/CSGHub#77]
目前测试Xinference只支持Huggingface和ModelScope的大模型下载，CSGHub是否可以实现与Xinference对接，下载大模型。

**Comment by Rader** [comment]
csghub是兼容 huggingface transformer sdk下载的，只需要替换hf的endpoint就可以。
方便发一下 Xinference的项目地址吗，我们测试一下看看

**Comment by wayneliu0019** [comment]
下面是使用transformer sdk从https://portal.opencsg.com拉取model启动服务的示例代码：
```
import gradio as gr
import os
from transformers import pipeline

os.environ['HF_ENDPOINT'] = "https://hub.opencsg.com/hf"  # 设置环境，更改HF的源指向传神社区

 # 直接使用传神社区的public model： https://portal.opencsg.com/models/AIWizards/opus-mt-en-zh
pipe = pipeline("translation", model="AIWizards/opus-mt-en-zh") 

def main(in_text):
  print(in_text)
  answer = pipe(in_text)
  print(answer)
  return answer[0]["translation_text"]

with gr.Blocks() as demo:
  gr.Markdown("""# Translation Engine!""")
  with gr.Row():
    with gr.Column():
      text1 = gr.Textbox(
            label="Input Text(EngLish)",
            lines=1,
        )
      output = gr.Textbox(label="Output Text(Chinese)")
      b1 = gr.Button("Translate!")
      b1.click(main, inputs=[text1], outputs=output)
  gr.Markdown("""#### powered by [Tassle](https://bit.ly/3LXMklV)""")


if __name__ == "__main__":
    demo.launch(debug=True)
```

**Comment by mushixun** [comment]
好的，目前我在本地搭建了个CSGHub和Xinference，把Xinference的HF_ENDPOINT修改成CSGHub的地址，测了下下载不了，不知道你们那是否测试通过的配置样例。

**Comment by wayneliu0019** [comment]
你可以尝尝直接在terminal中设置环境变量，下面是我刚刚测试的功能截图：
<img width="959" alt="image" src="https://github.com/OpenCSGs/CSGHub/assets/43563618/49cbfeea-361c-47a7-ab52-3abd76808723">

设置环境变量后，已经可以从传神社区下载model了

**Comment by mushixun** [comment]
好的，我试下，谢谢了！

**Comment by wayneliu0019** [comment]
有问题随时提哈！

**Comment by mushixun** [comment]
好像还不行，启动Xinference的脚本如下所示：
![image](https://github.com/OpenCSGs/CSGHub/assets/10143373/f088886e-ac60-47ea-9fa0-2f6df826a526)
CSGHub的模型库：
![image](https://github.com/OpenCSGs/CSGHub/assets/10143373/5cff4933-cc02-475e-98e0-ccf1777a26af)
Xinference的报错日志：
![image](https://github.com/OpenCSGs/CSGHub/assets/10143373/51ed33e3-158a-43c5-b207-a5a97d535158)

**Comment by wayneliu0019** [comment]
我大概知道问题在哪了：您现在部署的CSGHub系统是v0.2版本，支持transformer sdk的功能是在v0.3版本中提供的，请稍等两天，我们会在下周初更新v0.3，届时您只需要更新下csghub-server镜像即可。

**Comment by mushixun** [comment]
好的

**Comment by mushixun** [comment]
更新到了0.3版本貌似还不行，这是Xinference的报错日志
![image](https://github.com/OpenCSGs/CSGHub/assets/10143373/fcae9c62-f9f6-4acb-95db-e916da8ee3d6)
Xinference启动脚本：docker run -itd -v /data/xinference/models:/data/models -e XINFERENCE_HOME=/data/models -e HF_ENDPOINT=http://$CSGHub_IP/hf -p 9998:9997 xprobe/xinference:nightly-main-cpu xinference-local -H 0.0.0.0

**Comment by wayneliu0019** [comment]
从错误截图上看，新增的HF_ENDPOINT参数是有效的，将请求地址从huggingface转到了自部署csghubserver，但出现了404错误，您尝试重新拉取更新一下nginx服务的镜像（opencsg/csghub-nginx:latest或者registry.cn-beijing.aliyuncs.com/opencsg_public/csghub_nginx:latest），然后再试试看

ps：
早上更新代码和镜像后，nginx中的路由规则缺失了一条，后来才更新的nginx镜像。

**Comment by mushixun** [comment]
好的，可以了，谢谢！
