### ISSUE TITLE
csghub-sdk 上传单个文件，修改.gitattributes文件指定文件后缀*.safetensors filter=lfs diff=lfs merge=lfs -text使用lfs失败问题。

### ISSUE THREAD

**Issue by code9420** [OpenCSGs/csghub#837]
上传代码如下：
![image](https://github.com/user-attachments/assets/61329d2d-0dd1-4f6d-931e-d6953a8ccb9c)
我尝试搞了一个小的.safetensors文件上传成功了。
![image](https://github.com/user-attachments/assets/ebc25fc1-b867-411e-a1ae-189658b5cfc7)
但我使用huggingface真正的.safetensors二进制大文件上传报错失败，信息如下：
![image](https://github.com/user-attachments/assets/6a134c83-9e8d-43bd-99d0-20dfa0875ddf)
nginx服务日志报错信息如下：
![image](https://github.com/user-attachments/assets/9e8a3f9f-eb5d-43e5-a157-da0ec71f4d31)

**Comment by SeanHH86** [comment]
@code9420  在文件上传的过程中，csghub-server的日志中有什么错误吗？

**Comment by SeanHH86** [comment]
@code9420 
1. 根据nginx的错误提示，分析原因应该是网络数据传输超时引起的http连接断开而产生文件传输失败。
2. `http_upload_file` api 采用的是web http form表单的标准方式上传文件，对网络速度和通信超时都有很大的限制要求，会受到很多因素的影响，通常使用这种方式上传小文件是没有问题的。大文件建议使用git命令的方式上传。

**Comment by code9420** [comment]
好的
